name = input ("Masukkan nama kamu : ")
umur = (input("Masukkan umur kamu : "))
print(" Nama saya adalah " + name + " sedangkan umur saya adalah " + umur)
print("Nama saya adalah",name,"sedangkan umur saya",umur)
print (type(name))
print (type(umur))
print ("Name :" +name)
print ("Umur :" +umur)